/*
--------------------------------------------------
THIS FILE IS AUTOMAGICALLY GENERATED BY A SCRIPT.
DO NOT MODIFY THIS FILE.
--------------------------------------------------
*/

#pragma once
#include <atomic>
#include <cstdint>

class GlobalVariableManager {
public:
    GlobalVariableManager();

    static constexpr float PI = 3.141592653589793f;
    static constexpr float TWO_PI = 6.283185307179586f;
    static constexpr float PI_DIV_2 = 1.570796326794897;

    uint32_t getNumPolePairs();
    void setNumPolePairs(uint32_t value);

    bool getWantedCalibrationMode();
    void setWantedCalibrationMode(bool value);

    bool getActualCalibrationMode();
    void setActualCalibrationMode(bool value);

    float getAngle();
    void setAngle(float value);

    float getVelocity();
    void setVelocity(float value);

    float getAcceleration();
    void setAcceleration(float value);

    float getTorque();
    void setTorque(float value);

    float getAvgVelocity();
    void setAvgVelocity(float value);

    float getAvgAcceleration();
    void setAvgAcceleration(float value);

    float getAvgTorque();
    void setAvgTorque(float value);

    float getAvgLoopTimeFOC();
    void setAvgLoopTimeFOC(float value);

    uint32_t getVoltage();
    void setVoltage(uint32_t value);

    uint32_t getDrivingMode();
    void setDrivingMode(uint32_t value);

    uint32_t getCurrentLimitPhase();
    void setCurrentLimitPhase(uint32_t value);

    uint32_t getCurrentLimitBus();
    void setCurrentLimitBus(uint32_t value);

    float getIa();
    void setIa(float value);

    float getIb();
    void setIb(float value);

    float getIc();
    void setIc(float value);

    float getTorqueKp();
    void setTorqueKp(float value);

    float getTorqueKi();
    void setTorqueKi(float value);

    float getTorqueKd();
    void setTorqueKd(float value);

    float getTorqueSetpoint();
    void setTorqueSetpoint(float value);

    uint32_t getTorqueControlFrequency();
    void setTorqueControlFrequency(uint32_t value);

    float getVelocityKp();
    void setVelocityKp(float value);

    float getVelocityKi();
    void setVelocityKi(float value);

    float getVelocityKd();
    void setVelocityKd(float value);

    float getVelocitySetpoint();
    void setVelocitySetpoint(float value);

    uint32_t getVelocityControlFrequency();
    void setVelocityControlFrequency(uint32_t value);

    float getPositionKp();
    void setPositionKp(float value);

    float getPositionKi();
    void setPositionKi(float value);

    float getPositionKd();
    void setPositionKd(float value);

    float getPositionSetpoint();
    void setPositionSetpoint(float value);

    uint32_t getPositionControlFrequency();
    void setPositionControlFrequency(uint32_t value);

    static void atomic_store_float(std::atomic_uint32_t& atomicValue, float value);
    static float atomic_load_float(std::atomic_uint32_t& atomicValue);

private:
    std::atomic_uint32_t _numPolePairs{20};
    std::atomic_bool _wantedCalibrationMode{false};
    std::atomic_bool _actualCalibrationMode{false};
    std::atomic_uint32_t _angle{0};
    std::atomic_uint32_t _velocity{0};
    std::atomic_uint32_t _acceleration{0};
    std::atomic_uint32_t _torque{0};
    std::atomic_uint32_t _avgVelocity{0};
    std::atomic_uint32_t _avgAcceleration{0};
    std::atomic_uint32_t _avgTorque{0};
    std::atomic_uint32_t _avgLoopTimeFOC{0};
    std::atomic_uint32_t _voltage{0};
    std::atomic_uint32_t _drivingMode{0};
    std::atomic_uint32_t _currentLimitPhase{1000};
    std::atomic_uint32_t _currentLimitBus{5000};
    std::atomic_uint32_t _Ia{0};
    std::atomic_uint32_t _Ib{0};
    std::atomic_uint32_t _Ic{0};
    std::atomic_uint32_t _torqueKp{0};
    std::atomic_uint32_t _torqueKi{0};
    std::atomic_uint32_t _torqueKd{0};
    std::atomic_uint32_t _torqueSetpoint{0};
    std::atomic_uint32_t _torqueControlFrequency{1};
    std::atomic_uint32_t _velocityKp{0};
    std::atomic_uint32_t _velocityKi{0};
    std::atomic_uint32_t _velocityKd{0};
    std::atomic_uint32_t _velocitySetpoint{0};
    std::atomic_uint32_t _velocityControlFrequency{10};
    std::atomic_uint32_t _positionKp{0};
    std::atomic_uint32_t _positionKi{0};
    std::atomic_uint32_t _positionKd{0};
    std::atomic_uint32_t _positionSetpoint{0};
    std::atomic_uint32_t _positionControlFrequency{100};
};

extern GlobalVariableManager globalVariableManager;
