
variables = []
constValues = []

generatedFileIntro = [
    "/*\n",
    "-" * 50 + "\n",
    "THIS FILE IS AUTOMAGICALLY GENERATED BY A SCRIPT.\n",
    "DO NOT MODIFY THIS FILE.\n",
    "-" * 50 + "\n",
    "*/\n\n"
]

fileName = "GlobalVariableManager"
path = "components/GlobalVariableManager"
with open(f"{path}/Variables.txt", "r") as variableFile:
    activeArr = []
    for line in variableFile:
        line = line[0:-1]
        if (line == ""): continue
        if (line.startswith("# Variables")): continue
        if (line.startswith("# Consts")):
            variables = activeArr
            activeArr = []
            continue

        line = line.replace(" ", "")
        var0, var1, var2 = line.split(",")
        activeArr.append([var0, var1, var2])
    constValues = activeArr

with open(f"{path}/include/{fileName}.hpp", "w+") as header:
    header.writelines(generatedFileIntro)
    
    header.writelines([
        '#pragma once\n',
        '#include <atomic>\n',
        "#include <cstdint>\n",
        "\n",
        "class GlobalVariableManager {\n",
        "public:\n",
        "    GlobalVariableManager();\n",
        "\n"
    ])

    for constVal in constValues:
        header.write(f"    static constexpr {constVal[0]} {constVal[1]} = {constVal[2]};\n")
    header.write("\n");

    for var in variables:
        name = var[1][0].upper() + var[1][1:]
        header.writelines([
            f"    {var[0]} get{name}();\n",
            f"    void set{name}({var[0]} value);\n",
            "\n"
        ])
    
    header.writelines([
        f"    static void atomic_store_float(std::atomic_uint32_t& atomicValue, float value);\n"
        f"    static float atomic_load_float(std::atomic_uint32_t& atomicValue);\n"
    ])

    header.writelines([
        "\n",
        "private:\n"
    ])

    for var in variables:
        t = var[0] if var[0] != "float" else "uint32_t"
        value = var[2] if var[0] != "float" else "0"
        header.write(f"    std::atomic_{t} _{var[1]}{{{value}}};\n")
    
    header.writelines([
        "};\n",
        "\n"
        "extern GlobalVariableManager globalVariableManager;\n"
    ])

with open(f"{path}/{fileName}.cpp", "w+") as source:
    source.writelines(generatedFileIntro)
    
    source.writelines([
        '#include "GlobalVariableManager.hpp"\n',
        "#include <cstring>\n",
        "\n",
        "GlobalVariableManager globalVariableManager;\n"
        "\n",
        "GlobalVariableManager::GlobalVariableManager() {\n"
    ])

    for var in variables:
        if (var[0] != "float"): continue

        source.write(f"    atomic_store_float(_{var[1]}, {var[2]});\n")
    source.writelines([
        "}\n",
        "\n"
    ])

    source.writelines([
        "void GlobalVariableManager::atomic_store_float(std::atomic_uint32_t& atomicValue, float value) {\n",
        '    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");\n',
        "    uint32_t bits = 0;\n",
        "    std::memcpy(&bits, &value, sizeof(bits));\n",
        "    atomicValue.store(bits, std::memory_order_relaxed);\n",
        "}\n",
        "\n",
        "float GlobalVariableManager::atomic_load_float(std::atomic_uint32_t& atomicValue) {\n",
        '    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");\n',
        "    uint32_t bits = atomicValue.load(std::memory_order_relaxed);\n",
        "    float value = 0.0f;\n",
        "    std::memcpy(&value, &bits, sizeof(value));\n",
        "    return value;\n",
        "}\n"
    ])

    for var in variables:
        t = "uint32_t" if var[0] == "float" else var[0]
        name = var[1][0].upper() + var[1][1:]

        if (var[0]) == "float":
            loadLine = f"return atomic_load_float(_{var[1]});\n"
            storeLine = f"atomic_store_float(_{var[1]}, value);\n"
        else:
            loadLine = f"return _{var[1]}.load(std::memory_order_relaxed);\n"
            storeLine = f"_{var[1]}.store(value, std::memory_order_relaxed);\n"

        source.writelines([
            f"{var[0]} GlobalVariableManager::get{name}() {{\n",
            "    " + loadLine,
            "}\n",
            "\n",
            f"void GlobalVariableManager::set{name}({var[0]} value) {{\n",
            "    " + storeLine,
            "}\n",
            "\n"
        ])
