/*
--------------------------------------------------
THIS FILE IS AUTOMAGICALLY GENERATED BY A SCRIPT.
DO NOT MODIFY THIS FILE.
--------------------------------------------------
*/

#include "GlobalVariableManager.hpp"
#include <cstring>

GlobalVariableManager globalVariableManager;

GlobalVariableManager::GlobalVariableManager() {
    atomic_store_float(_angle, 0.0f);
    atomic_store_float(_velocity, 0.0f);
    atomic_store_float(_acceleration, 0.0f);
    atomic_store_float(_torque, 0.0f);
    atomic_store_float(_avgVelocity, 0.0f);
    atomic_store_float(_avgAcceleration, 0.0f);
    atomic_store_float(_avgTorque, 0.0f);
    atomic_store_float(_avgLoopTimeFOC, 0.0f);
    atomic_store_float(_Ia, 0.0f);
    atomic_store_float(_Ib, 0.0f);
    atomic_store_float(_Ic, 0.0f);
    atomic_store_float(_torqueKp, 0.0f);
    atomic_store_float(_torqueKi, 0.0f);
    atomic_store_float(_torqueKd, 0.0f);
    atomic_store_float(_torqueSetpoint, 0.0f);
    atomic_store_float(_velocityKp, 0.0f);
    atomic_store_float(_velocityKi, 0.0f);
    atomic_store_float(_velocityKd, 0.0f);
    atomic_store_float(_velocitySetpoint, 0.0f);
    atomic_store_float(_positionKp, 0.0f);
    atomic_store_float(_positionKi, 0.0f);
    atomic_store_float(_positionKd, 0.0f);
    atomic_store_float(_positionSetpoint, 0.0f);
}

void GlobalVariableManager::atomic_store_float(std::atomic_uint32_t& atomicValue, float value) {
    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");
    uint32_t bits = 0;
    std::memcpy(&bits, &value, sizeof(bits));
    atomicValue.store(bits, std::memory_order_relaxed);
}

float GlobalVariableManager::atomic_load_float(std::atomic_uint32_t& atomicValue) {
    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");
    uint32_t bits = atomicValue.load(std::memory_order_relaxed);
    float value = 0.0f;
    std::memcpy(&value, &bits, sizeof(value));
    return value;
}
uint32_t GlobalVariableManager::getUdpFromPeripheralBuffer(uint8_t* value, uint32_t capacity) {
    if (capacity < _udpFromPeripheralBufferSize) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromPeripheralBufferMutex);
    memcpy(value, _udpFromPeripheralBuffer, _udpFromPeripheralBufferSize);
    return _udpFromPeripheralBufferSize;
}

uint32_t GlobalVariableManager::setUdpFromPeripheralBuffer(const uint8_t* value, uint32_t capacity) {
    if (capacity > _udpFromPeripheralBufferCapacity) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromPeripheralBufferMutex);
    memcpy(_udpFromPeripheralBuffer, value, capacity);
    _udpFromPeripheralBufferSize = capacity;
    return capacity;
}

uint32_t GlobalVariableManager::getNumPolePairs() {
    return _numPolePairs.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setNumPolePairs(uint32_t value) {
    _numPolePairs.store(value, std::memory_order_relaxed);
}

bool GlobalVariableManager::getWantedCalibrationMode() {
    return _wantedCalibrationMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setWantedCalibrationMode(bool value) {
    _wantedCalibrationMode.store(value, std::memory_order_relaxed);
}

bool GlobalVariableManager::getActualCalibrationMode() {
    return _actualCalibrationMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setActualCalibrationMode(bool value) {
    _actualCalibrationMode.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getAngle() {
    return atomic_load_float(_angle);
}

void GlobalVariableManager::setAngle(float value) {
    atomic_store_float(_angle, value);
}

float GlobalVariableManager::getVelocity() {
    return atomic_load_float(_velocity);
}

void GlobalVariableManager::setVelocity(float value) {
    atomic_store_float(_velocity, value);
}

float GlobalVariableManager::getAcceleration() {
    return atomic_load_float(_acceleration);
}

void GlobalVariableManager::setAcceleration(float value) {
    atomic_store_float(_acceleration, value);
}

float GlobalVariableManager::getTorque() {
    return atomic_load_float(_torque);
}

void GlobalVariableManager::setTorque(float value) {
    atomic_store_float(_torque, value);
}

float GlobalVariableManager::getAvgVelocity() {
    return atomic_load_float(_avgVelocity);
}

void GlobalVariableManager::setAvgVelocity(float value) {
    atomic_store_float(_avgVelocity, value);
}

float GlobalVariableManager::getAvgAcceleration() {
    return atomic_load_float(_avgAcceleration);
}

void GlobalVariableManager::setAvgAcceleration(float value) {
    atomic_store_float(_avgAcceleration, value);
}

float GlobalVariableManager::getAvgTorque() {
    return atomic_load_float(_avgTorque);
}

void GlobalVariableManager::setAvgTorque(float value) {
    atomic_store_float(_avgTorque, value);
}

float GlobalVariableManager::getAvgLoopTimeFOC() {
    return atomic_load_float(_avgLoopTimeFOC);
}

void GlobalVariableManager::setAvgLoopTimeFOC(float value) {
    atomic_store_float(_avgLoopTimeFOC, value);
}

uint32_t GlobalVariableManager::getVoltage() {
    return _voltage.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setVoltage(uint32_t value) {
    _voltage.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getDrivingMode() {
    return _drivingMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setDrivingMode(uint32_t value) {
    _drivingMode.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getCurrentLimitPhase() {
    return _currentLimitPhase.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setCurrentLimitPhase(uint32_t value) {
    _currentLimitPhase.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getCurrentLimitBus() {
    return _currentLimitBus.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setCurrentLimitBus(uint32_t value) {
    _currentLimitBus.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getIa() {
    return atomic_load_float(_Ia);
}

void GlobalVariableManager::setIa(float value) {
    atomic_store_float(_Ia, value);
}

float GlobalVariableManager::getIb() {
    return atomic_load_float(_Ib);
}

void GlobalVariableManager::setIb(float value) {
    atomic_store_float(_Ib, value);
}

float GlobalVariableManager::getIc() {
    return atomic_load_float(_Ic);
}

void GlobalVariableManager::setIc(float value) {
    atomic_store_float(_Ic, value);
}

float GlobalVariableManager::getTorqueKp() {
    return atomic_load_float(_torqueKp);
}

void GlobalVariableManager::setTorqueKp(float value) {
    atomic_store_float(_torqueKp, value);
}

float GlobalVariableManager::getTorqueKi() {
    return atomic_load_float(_torqueKi);
}

void GlobalVariableManager::setTorqueKi(float value) {
    atomic_store_float(_torqueKi, value);
}

float GlobalVariableManager::getTorqueKd() {
    return atomic_load_float(_torqueKd);
}

void GlobalVariableManager::setTorqueKd(float value) {
    atomic_store_float(_torqueKd, value);
}

float GlobalVariableManager::getTorqueSetpoint() {
    return atomic_load_float(_torqueSetpoint);
}

void GlobalVariableManager::setTorqueSetpoint(float value) {
    atomic_store_float(_torqueSetpoint, value);
}

uint32_t GlobalVariableManager::getTorqueControlFrequency() {
    return _torqueControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTorqueControlFrequency(uint32_t value) {
    _torqueControlFrequency.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getVelocityKp() {
    return atomic_load_float(_velocityKp);
}

void GlobalVariableManager::setVelocityKp(float value) {
    atomic_store_float(_velocityKp, value);
}

float GlobalVariableManager::getVelocityKi() {
    return atomic_load_float(_velocityKi);
}

void GlobalVariableManager::setVelocityKi(float value) {
    atomic_store_float(_velocityKi, value);
}

float GlobalVariableManager::getVelocityKd() {
    return atomic_load_float(_velocityKd);
}

void GlobalVariableManager::setVelocityKd(float value) {
    atomic_store_float(_velocityKd, value);
}

float GlobalVariableManager::getVelocitySetpoint() {
    return atomic_load_float(_velocitySetpoint);
}

void GlobalVariableManager::setVelocitySetpoint(float value) {
    atomic_store_float(_velocitySetpoint, value);
}

uint32_t GlobalVariableManager::getVelocityControlFrequency() {
    return _velocityControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setVelocityControlFrequency(uint32_t value) {
    _velocityControlFrequency.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getPositionKp() {
    return atomic_load_float(_positionKp);
}

void GlobalVariableManager::setPositionKp(float value) {
    atomic_store_float(_positionKp, value);
}

float GlobalVariableManager::getPositionKi() {
    return atomic_load_float(_positionKi);
}

void GlobalVariableManager::setPositionKi(float value) {
    atomic_store_float(_positionKi, value);
}

float GlobalVariableManager::getPositionKd() {
    return atomic_load_float(_positionKd);
}

void GlobalVariableManager::setPositionKd(float value) {
    atomic_store_float(_positionKd, value);
}

float GlobalVariableManager::getPositionSetpoint() {
    return atomic_load_float(_positionSetpoint);
}

void GlobalVariableManager::setPositionSetpoint(float value) {
    atomic_store_float(_positionSetpoint, value);
}

uint32_t GlobalVariableManager::getPositionControlFrequency() {
    return _positionControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setPositionControlFrequency(uint32_t value) {
    _positionControlFrequency.store(value, std::memory_order_relaxed);
}

