/*
--------------------------------------------------
THIS FILE IS AUTOMAGICALLY GENERATED BY A SCRIPT.
DO NOT MODIFY THIS FILE.
--------------------------------------------------
*/

#include "GlobalVariableManager.hpp"
#include <cstring>

GlobalVariableManager globalVariableManager;

GlobalVariableManager::GlobalVariableManager() {
    atomic_store_float(_wantedPhaseA, 0.0f);
    atomic_store_float(_wantedPhaseB, 0.0f);
    atomic_store_float(_wantedPhaseC, 0.0f);
    atomic_store_float(_computedPhaseA, 0.0f);
    atomic_store_float(_computedPhaseB, 0.0f);
    atomic_store_float(_computedPhaseC, 0.0f);
    atomic_store_float(_angle, 0.0f);
    atomic_store_float(_velocity, 0.0f);
    atomic_store_float(_acceleration, 0.0f);
    atomic_store_float(_torque, 0.0f);
    atomic_store_float(_avgVelocity, 0.0f);
    atomic_store_float(_avgAcceleration, 0.0f);
    atomic_store_float(_avgTorque, 0.0f);
    atomic_store_float(_busVoltage, 0);
    atomic_store_float(_busCurrent, 0);
    atomic_store_float(_phaseRMSVoltage, 0.0f);
    atomic_store_float(_Ia, 0.0f);
    atomic_store_float(_Ib, 0.0f);
    atomic_store_float(_Ic, 0.0f);
    atomic_store_float(_torqueKp, 0.0f);
    atomic_store_float(_torqueKi, 0.0f);
    atomic_store_float(_torqueKd, 0.0f);
    atomic_store_float(_torqueLimit, 0.0f);
    atomic_store_float(_torqueSetpoint, 0.0f);
    atomic_store_float(_velocityKp, 0.0f);
    atomic_store_float(_velocityKi, 0.0f);
    atomic_store_float(_velocityKd, 0.0f);
    atomic_store_float(_velocityLimit, 0.0f);
    atomic_store_float(_velocitySetpoint, 0.0f);
    atomic_store_float(_positionKp, 0.0f);
    atomic_store_float(_positionKi, 0.0f);
    atomic_store_float(_positionKd, 0.0f);
    atomic_store_float(_positionSetpoint, 0.0f);
    atomic_store_float(_accX, 0.0f);
    atomic_store_float(_accY, 0.0f);
    atomic_store_float(_accZ, 0.0f);
    atomic_store_float(_gyroX, 0.0f);
    atomic_store_float(_gyroY, 0.0f);
    atomic_store_float(_gyroZ, 0.0f);
    atomic_store_float(_udpDataDebugFloat0, 0.0f);
    atomic_store_float(_udpDataDebugFloat1, 0.0f);
    atomic_store_float(_udpDataDebugFloat2, 0.0f);
    atomic_store_float(_udpDataDebugFloat3, 0.0f);
    atomic_store_float(_udpCommandDebugFloat0, 0.0f);
    atomic_store_float(_udpCommandDebugFloat1, 0.0f);
    atomic_store_float(_udpCommandDebugFloat2, 0.0f);
    atomic_store_float(_udpCommandDebugFloat3, 0.0f);
    atomic_store_float(_tcpDataDebugFloat0, 0.0f);
    atomic_store_float(_tcpDataDebugFloat1, 0.0f);
    atomic_store_float(_tcpDataDebugFloat2, 0.0f);
    atomic_store_float(_tcpDataDebugFloat3, 0.0f);
    atomic_store_float(_tcpCommandDebugFloat0, 0.0f);
    atomic_store_float(_tcpCommandDebugFloat1, 0.0f);
    atomic_store_float(_tcpCommandDebugFloat2, 0.0f);
    atomic_store_float(_tcpCommandDebugFloat3, 0.0f);
}

void GlobalVariableManager::atomic_store_float(std::atomic_uint32_t& atomicValue, float value) {
    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");
    uint32_t bits = 0;
    std::memcpy(&bits, &value, sizeof(bits));
    atomicValue.store(bits, std::memory_order_relaxed);
}

float GlobalVariableManager::atomic_load_float(std::atomic_uint32_t& atomicValue) {
    static_assert(sizeof(float) == sizeof(uint32_t), "float must be 32-bit");
    uint32_t bits = atomicValue.load(std::memory_order_relaxed);
    float value = 0.0f;
    std::memcpy(&value, &bits, sizeof(value));
    return value;
}
float GlobalVariableManager::getWantedPhaseA() {
    return atomic_load_float(_wantedPhaseA);
}

void GlobalVariableManager::setWantedPhaseA(float value) {
    atomic_store_float(_wantedPhaseA, value);
}

float GlobalVariableManager::getWantedPhaseB() {
    return atomic_load_float(_wantedPhaseB);
}

void GlobalVariableManager::setWantedPhaseB(float value) {
    atomic_store_float(_wantedPhaseB, value);
}

float GlobalVariableManager::getWantedPhaseC() {
    return atomic_load_float(_wantedPhaseC);
}

void GlobalVariableManager::setWantedPhaseC(float value) {
    atomic_store_float(_wantedPhaseC, value);
}

float GlobalVariableManager::getComputedPhaseA() {
    return atomic_load_float(_computedPhaseA);
}

void GlobalVariableManager::setComputedPhaseA(float value) {
    atomic_store_float(_computedPhaseA, value);
}

float GlobalVariableManager::getComputedPhaseB() {
    return atomic_load_float(_computedPhaseB);
}

void GlobalVariableManager::setComputedPhaseB(float value) {
    atomic_store_float(_computedPhaseB, value);
}

float GlobalVariableManager::getComputedPhaseC() {
    return atomic_load_float(_computedPhaseC);
}

void GlobalVariableManager::setComputedPhaseC(float value) {
    atomic_store_float(_computedPhaseC, value);
}

uint32_t GlobalVariableManager::getUdpAsPeripheralHeader() {
    return _udpAsPeripheralHeader.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpAsPeripheralHeader(uint32_t value) {
    _udpAsPeripheralHeader.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getUdpFromPeripheralBuffer(uint8_t* value, uint32_t capacity, bool empty) {
    if (capacity < _udpFromPeripheralBufferSize) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromPeripheralBufferMutex);
    memcpy(value, _udpFromPeripheralBuffer, _udpFromPeripheralBufferSize);
    
    uint32_t out = _udpFromPeripheralBufferSize;
    if (empty) { _udpFromPeripheralBufferSize = 0; };
    return out;
}

uint32_t GlobalVariableManager::setUdpFromPeripheralBuffer(const uint8_t* value, uint32_t capacity) {
    if (capacity > _udpFromPeripheralBufferCapacity) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromPeripheralBufferMutex);
    memcpy(_udpFromPeripheralBuffer, value, capacity);
    _udpFromPeripheralBufferSize = capacity;
    return capacity;
}

uint32_t GlobalVariableManager::getUdpFromControllerBuffer(uint8_t* value, uint32_t capacity, bool empty) {
    if (capacity < _udpFromControllerBufferSize) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromControllerBufferMutex);
    memcpy(value, _udpFromControllerBuffer, _udpFromControllerBufferSize);
    
    uint32_t out = _udpFromControllerBufferSize;
    if (empty) { _udpFromControllerBufferSize = 0; };
    return out;
}

uint32_t GlobalVariableManager::setUdpFromControllerBuffer(const uint8_t* value, uint32_t capacity) {
    if (capacity > _udpFromControllerBufferCapacity) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_udpFromControllerBufferMutex);
    memcpy(_udpFromControllerBuffer, value, capacity);
    _udpFromControllerBufferSize = capacity;
    return capacity;
}

uint32_t GlobalVariableManager::getTcpFromPeripheralBuffer(uint8_t* value, uint32_t capacity, bool empty) {
    if (capacity < _tcpFromPeripheralBufferSize) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_tcpFromPeripheralBufferMutex);
    memcpy(value, _tcpFromPeripheralBuffer, _tcpFromPeripheralBufferSize);
    
    uint32_t out = _tcpFromPeripheralBufferSize;
    if (empty) { _tcpFromPeripheralBufferSize = 0; };
    return out;
}

uint32_t GlobalVariableManager::setTcpFromPeripheralBuffer(const uint8_t* value, uint32_t capacity) {
    if (capacity > _tcpFromPeripheralBufferCapacity) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_tcpFromPeripheralBufferMutex);
    memcpy(_tcpFromPeripheralBuffer, value, capacity);
    _tcpFromPeripheralBufferSize = capacity;
    return capacity;
}

uint32_t GlobalVariableManager::getTcpFromControllerBuffer(uint8_t* value, uint32_t capacity, bool empty) {
    if (capacity < _tcpFromControllerBufferSize) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_tcpFromControllerBufferMutex);
    memcpy(value, _tcpFromControllerBuffer, _tcpFromControllerBufferSize);
    
    uint32_t out = _tcpFromControllerBufferSize;
    if (empty) { _tcpFromControllerBufferSize = 0; };
    return out;
}

uint32_t GlobalVariableManager::setTcpFromControllerBuffer(const uint8_t* value, uint32_t capacity) {
    if (capacity > _tcpFromControllerBufferCapacity) {
        return 0;
    }
    
    std::lock_guard<std::mutex> lock(_tcpFromControllerBufferMutex);
    memcpy(_tcpFromControllerBuffer, value, capacity);
    _tcpFromControllerBufferSize = capacity;
    return capacity;
}

uint32_t GlobalVariableManager::getNumPolePairs() {
    return _numPolePairs.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setNumPolePairs(uint32_t value) {
    _numPolePairs.store(value, std::memory_order_relaxed);
}

bool GlobalVariableManager::getWantedCalibrationMode() {
    return _wantedCalibrationMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setWantedCalibrationMode(bool value) {
    _wantedCalibrationMode.store(value, std::memory_order_relaxed);
}

bool GlobalVariableManager::getActualCalibrationMode() {
    return _actualCalibrationMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setActualCalibrationMode(bool value) {
    _actualCalibrationMode.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getAngle() {
    return atomic_load_float(_angle);
}

void GlobalVariableManager::setAngle(float value) {
    atomic_store_float(_angle, value);
}

float GlobalVariableManager::getVelocity() {
    return atomic_load_float(_velocity);
}

void GlobalVariableManager::setVelocity(float value) {
    atomic_store_float(_velocity, value);
}

float GlobalVariableManager::getAcceleration() {
    return atomic_load_float(_acceleration);
}

void GlobalVariableManager::setAcceleration(float value) {
    atomic_store_float(_acceleration, value);
}

float GlobalVariableManager::getTorque() {
    return atomic_load_float(_torque);
}

void GlobalVariableManager::setTorque(float value) {
    atomic_store_float(_torque, value);
}

float GlobalVariableManager::getAvgVelocity() {
    return atomic_load_float(_avgVelocity);
}

void GlobalVariableManager::setAvgVelocity(float value) {
    atomic_store_float(_avgVelocity, value);
}

float GlobalVariableManager::getAvgAcceleration() {
    return atomic_load_float(_avgAcceleration);
}

void GlobalVariableManager::setAvgAcceleration(float value) {
    atomic_store_float(_avgAcceleration, value);
}

float GlobalVariableManager::getAvgTorque() {
    return atomic_load_float(_avgTorque);
}

void GlobalVariableManager::setAvgTorque(float value) {
    atomic_store_float(_avgTorque, value);
}

uint32_t GlobalVariableManager::getAvgLoopTimeFOC() {
    return _avgLoopTimeFOC.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setAvgLoopTimeFOC(uint32_t value) {
    _avgLoopTimeFOC.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getAvgLoopTimeSecondary() {
    return _avgLoopTimeSecondary.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setAvgLoopTimeSecondary(uint32_t value) {
    _avgLoopTimeSecondary.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getErrorFlags() {
    return _errorFlags.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setErrorFlags(uint32_t value) {
    _errorFlags.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getBoardState() {
    return _boardState.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setBoardState(uint32_t value) {
    _boardState.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getLedStatus() {
    return _ledStatus.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setLedStatus(uint32_t value) {
    _ledStatus.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getButtonStatus() {
    return _buttonStatus.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setButtonStatus(uint32_t value) {
    _buttonStatus.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getBusVoltage() {
    return atomic_load_float(_busVoltage);
}

void GlobalVariableManager::setBusVoltage(float value) {
    atomic_store_float(_busVoltage, value);
}

float GlobalVariableManager::getBusCurrent() {
    return atomic_load_float(_busCurrent);
}

void GlobalVariableManager::setBusCurrent(float value) {
    atomic_store_float(_busCurrent, value);
}

uint32_t GlobalVariableManager::getDrivingMode() {
    return _drivingMode.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setDrivingMode(uint32_t value) {
    _drivingMode.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getCurrentLimitPhase() {
    return _currentLimitPhase.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setCurrentLimitPhase(uint32_t value) {
    _currentLimitPhase.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getCurrentLimitBus() {
    return _currentLimitBus.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setCurrentLimitBus(uint32_t value) {
    _currentLimitBus.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getPhaseRMSVoltage() {
    return atomic_load_float(_phaseRMSVoltage);
}

void GlobalVariableManager::setPhaseRMSVoltage(float value) {
    atomic_store_float(_phaseRMSVoltage, value);
}

float GlobalVariableManager::getIa() {
    return atomic_load_float(_Ia);
}

void GlobalVariableManager::setIa(float value) {
    atomic_store_float(_Ia, value);
}

float GlobalVariableManager::getIb() {
    return atomic_load_float(_Ib);
}

void GlobalVariableManager::setIb(float value) {
    atomic_store_float(_Ib, value);
}

float GlobalVariableManager::getIc() {
    return atomic_load_float(_Ic);
}

void GlobalVariableManager::setIc(float value) {
    atomic_store_float(_Ic, value);
}

float GlobalVariableManager::getTorqueKp() {
    return atomic_load_float(_torqueKp);
}

void GlobalVariableManager::setTorqueKp(float value) {
    atomic_store_float(_torqueKp, value);
}

float GlobalVariableManager::getTorqueKi() {
    return atomic_load_float(_torqueKi);
}

void GlobalVariableManager::setTorqueKi(float value) {
    atomic_store_float(_torqueKi, value);
}

float GlobalVariableManager::getTorqueKd() {
    return atomic_load_float(_torqueKd);
}

void GlobalVariableManager::setTorqueKd(float value) {
    atomic_store_float(_torqueKd, value);
}

float GlobalVariableManager::getTorqueLimit() {
    return atomic_load_float(_torqueLimit);
}

void GlobalVariableManager::setTorqueLimit(float value) {
    atomic_store_float(_torqueLimit, value);
}

float GlobalVariableManager::getTorqueSetpoint() {
    return atomic_load_float(_torqueSetpoint);
}

void GlobalVariableManager::setTorqueSetpoint(float value) {
    atomic_store_float(_torqueSetpoint, value);
}

uint32_t GlobalVariableManager::getTorqueControlFrequency() {
    return _torqueControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTorqueControlFrequency(uint32_t value) {
    _torqueControlFrequency.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getVelocityKp() {
    return atomic_load_float(_velocityKp);
}

void GlobalVariableManager::setVelocityKp(float value) {
    atomic_store_float(_velocityKp, value);
}

float GlobalVariableManager::getVelocityKi() {
    return atomic_load_float(_velocityKi);
}

void GlobalVariableManager::setVelocityKi(float value) {
    atomic_store_float(_velocityKi, value);
}

float GlobalVariableManager::getVelocityKd() {
    return atomic_load_float(_velocityKd);
}

void GlobalVariableManager::setVelocityKd(float value) {
    atomic_store_float(_velocityKd, value);
}

float GlobalVariableManager::getVelocityLimit() {
    return atomic_load_float(_velocityLimit);
}

void GlobalVariableManager::setVelocityLimit(float value) {
    atomic_store_float(_velocityLimit, value);
}

float GlobalVariableManager::getVelocitySetpoint() {
    return atomic_load_float(_velocitySetpoint);
}

void GlobalVariableManager::setVelocitySetpoint(float value) {
    atomic_store_float(_velocitySetpoint, value);
}

uint32_t GlobalVariableManager::getVelocityControlFrequency() {
    return _velocityControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setVelocityControlFrequency(uint32_t value) {
    _velocityControlFrequency.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getPositionKp() {
    return atomic_load_float(_positionKp);
}

void GlobalVariableManager::setPositionKp(float value) {
    atomic_store_float(_positionKp, value);
}

float GlobalVariableManager::getPositionKi() {
    return atomic_load_float(_positionKi);
}

void GlobalVariableManager::setPositionKi(float value) {
    atomic_store_float(_positionKi, value);
}

float GlobalVariableManager::getPositionKd() {
    return atomic_load_float(_positionKd);
}

void GlobalVariableManager::setPositionKd(float value) {
    atomic_store_float(_positionKd, value);
}

float GlobalVariableManager::getPositionSetpoint() {
    return atomic_load_float(_positionSetpoint);
}

void GlobalVariableManager::setPositionSetpoint(float value) {
    atomic_store_float(_positionSetpoint, value);
}

uint32_t GlobalVariableManager::getPositionControlFrequency() {
    return _positionControlFrequency.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setPositionControlFrequency(uint32_t value) {
    _positionControlFrequency.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getAccX() {
    return atomic_load_float(_accX);
}

void GlobalVariableManager::setAccX(float value) {
    atomic_store_float(_accX, value);
}

float GlobalVariableManager::getAccY() {
    return atomic_load_float(_accY);
}

void GlobalVariableManager::setAccY(float value) {
    atomic_store_float(_accY, value);
}

float GlobalVariableManager::getAccZ() {
    return atomic_load_float(_accZ);
}

void GlobalVariableManager::setAccZ(float value) {
    atomic_store_float(_accZ, value);
}

float GlobalVariableManager::getGyroX() {
    return atomic_load_float(_gyroX);
}

void GlobalVariableManager::setGyroX(float value) {
    atomic_store_float(_gyroX, value);
}

float GlobalVariableManager::getGyroY() {
    return atomic_load_float(_gyroY);
}

void GlobalVariableManager::setGyroY(float value) {
    atomic_store_float(_gyroY, value);
}

float GlobalVariableManager::getGyroZ() {
    return atomic_load_float(_gyroZ);
}

void GlobalVariableManager::setGyroZ(float value) {
    atomic_store_float(_gyroZ, value);
}

float GlobalVariableManager::getUdpDataDebugFloat0() {
    return atomic_load_float(_udpDataDebugFloat0);
}

void GlobalVariableManager::setUdpDataDebugFloat0(float value) {
    atomic_store_float(_udpDataDebugFloat0, value);
}

float GlobalVariableManager::getUdpDataDebugFloat1() {
    return atomic_load_float(_udpDataDebugFloat1);
}

void GlobalVariableManager::setUdpDataDebugFloat1(float value) {
    atomic_store_float(_udpDataDebugFloat1, value);
}

float GlobalVariableManager::getUdpDataDebugFloat2() {
    return atomic_load_float(_udpDataDebugFloat2);
}

void GlobalVariableManager::setUdpDataDebugFloat2(float value) {
    atomic_store_float(_udpDataDebugFloat2, value);
}

float GlobalVariableManager::getUdpDataDebugFloat3() {
    return atomic_load_float(_udpDataDebugFloat3);
}

void GlobalVariableManager::setUdpDataDebugFloat3(float value) {
    atomic_store_float(_udpDataDebugFloat3, value);
}

int32_t GlobalVariableManager::getUdpDataDebugInt0() {
    return _udpDataDebugInt0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpDataDebugInt0(int32_t value) {
    _udpDataDebugInt0.store(value, std::memory_order_relaxed);
}

int32_t GlobalVariableManager::getUdpDataDebugInt1() {
    return _udpDataDebugInt1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpDataDebugInt1(int32_t value) {
    _udpDataDebugInt1.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getUdpDataDebugUint0() {
    return _udpDataDebugUint0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpDataDebugUint0(uint32_t value) {
    _udpDataDebugUint0.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getUdpDataDebugUint1() {
    return _udpDataDebugUint1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpDataDebugUint1(uint32_t value) {
    _udpDataDebugUint1.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getUdpCommandDebugFloat0() {
    return atomic_load_float(_udpCommandDebugFloat0);
}

void GlobalVariableManager::setUdpCommandDebugFloat0(float value) {
    atomic_store_float(_udpCommandDebugFloat0, value);
}

float GlobalVariableManager::getUdpCommandDebugFloat1() {
    return atomic_load_float(_udpCommandDebugFloat1);
}

void GlobalVariableManager::setUdpCommandDebugFloat1(float value) {
    atomic_store_float(_udpCommandDebugFloat1, value);
}

float GlobalVariableManager::getUdpCommandDebugFloat2() {
    return atomic_load_float(_udpCommandDebugFloat2);
}

void GlobalVariableManager::setUdpCommandDebugFloat2(float value) {
    atomic_store_float(_udpCommandDebugFloat2, value);
}

float GlobalVariableManager::getUdpCommandDebugFloat3() {
    return atomic_load_float(_udpCommandDebugFloat3);
}

void GlobalVariableManager::setUdpCommandDebugFloat3(float value) {
    atomic_store_float(_udpCommandDebugFloat3, value);
}

int32_t GlobalVariableManager::getUdpCommandDebugInt0() {
    return _udpCommandDebugInt0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpCommandDebugInt0(int32_t value) {
    _udpCommandDebugInt0.store(value, std::memory_order_relaxed);
}

int32_t GlobalVariableManager::getUdpCommandDebugInt1() {
    return _udpCommandDebugInt1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpCommandDebugInt1(int32_t value) {
    _udpCommandDebugInt1.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getUdpCommandDebugUint0() {
    return _udpCommandDebugUint0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpCommandDebugUint0(uint32_t value) {
    _udpCommandDebugUint0.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getUdpCommandDebugUint1() {
    return _udpCommandDebugUint1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setUdpCommandDebugUint1(uint32_t value) {
    _udpCommandDebugUint1.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getTcpDataDebugFloat0() {
    return atomic_load_float(_tcpDataDebugFloat0);
}

void GlobalVariableManager::setTcpDataDebugFloat0(float value) {
    atomic_store_float(_tcpDataDebugFloat0, value);
}

float GlobalVariableManager::getTcpDataDebugFloat1() {
    return atomic_load_float(_tcpDataDebugFloat1);
}

void GlobalVariableManager::setTcpDataDebugFloat1(float value) {
    atomic_store_float(_tcpDataDebugFloat1, value);
}

float GlobalVariableManager::getTcpDataDebugFloat2() {
    return atomic_load_float(_tcpDataDebugFloat2);
}

void GlobalVariableManager::setTcpDataDebugFloat2(float value) {
    atomic_store_float(_tcpDataDebugFloat2, value);
}

float GlobalVariableManager::getTcpDataDebugFloat3() {
    return atomic_load_float(_tcpDataDebugFloat3);
}

void GlobalVariableManager::setTcpDataDebugFloat3(float value) {
    atomic_store_float(_tcpDataDebugFloat3, value);
}

int32_t GlobalVariableManager::getTcpDataDebugInt0() {
    return _tcpDataDebugInt0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpDataDebugInt0(int32_t value) {
    _tcpDataDebugInt0.store(value, std::memory_order_relaxed);
}

int32_t GlobalVariableManager::getTcpDataDebugInt1() {
    return _tcpDataDebugInt1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpDataDebugInt1(int32_t value) {
    _tcpDataDebugInt1.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getTcpDataDebugUint0() {
    return _tcpDataDebugUint0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpDataDebugUint0(uint32_t value) {
    _tcpDataDebugUint0.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getTcpDataDebugUint1() {
    return _tcpDataDebugUint1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpDataDebugUint1(uint32_t value) {
    _tcpDataDebugUint1.store(value, std::memory_order_relaxed);
}

float GlobalVariableManager::getTcpCommandDebugFloat0() {
    return atomic_load_float(_tcpCommandDebugFloat0);
}

void GlobalVariableManager::setTcpCommandDebugFloat0(float value) {
    atomic_store_float(_tcpCommandDebugFloat0, value);
}

float GlobalVariableManager::getTcpCommandDebugFloat1() {
    return atomic_load_float(_tcpCommandDebugFloat1);
}

void GlobalVariableManager::setTcpCommandDebugFloat1(float value) {
    atomic_store_float(_tcpCommandDebugFloat1, value);
}

float GlobalVariableManager::getTcpCommandDebugFloat2() {
    return atomic_load_float(_tcpCommandDebugFloat2);
}

void GlobalVariableManager::setTcpCommandDebugFloat2(float value) {
    atomic_store_float(_tcpCommandDebugFloat2, value);
}

float GlobalVariableManager::getTcpCommandDebugFloat3() {
    return atomic_load_float(_tcpCommandDebugFloat3);
}

void GlobalVariableManager::setTcpCommandDebugFloat3(float value) {
    atomic_store_float(_tcpCommandDebugFloat3, value);
}

int32_t GlobalVariableManager::getTcpCommandDebugInt0() {
    return _tcpCommandDebugInt0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpCommandDebugInt0(int32_t value) {
    _tcpCommandDebugInt0.store(value, std::memory_order_relaxed);
}

int32_t GlobalVariableManager::getTcpCommandDebugInt1() {
    return _tcpCommandDebugInt1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpCommandDebugInt1(int32_t value) {
    _tcpCommandDebugInt1.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getTcpCommandDebugUint0() {
    return _tcpCommandDebugUint0.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpCommandDebugUint0(uint32_t value) {
    _tcpCommandDebugUint0.store(value, std::memory_order_relaxed);
}

uint32_t GlobalVariableManager::getTcpCommandDebugUint1() {
    return _tcpCommandDebugUint1.load(std::memory_order_relaxed);
}

void GlobalVariableManager::setTcpCommandDebugUint1(uint32_t value) {
    _tcpCommandDebugUint1.store(value, std::memory_order_relaxed);
}

